language: go

go:
- '1.11'

env:
  - GO111MODULE=on

  OS: linux

before_install:
  - go get -t -v ./...

script:
  - 'bash ./travis/test_coverage.sh;'

after_success:
  - bash <(curl -s https://codecov.io/bash)