language: go

go:
- '1.11'

env:
  - GO111MODULE=on

  OS: linux

before_install:
  - go get -t -v ./...

install:
  - go get golang.org/x/tools/cmd/goimports
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go mod vendor

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests.sh; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests.sh; fi'
  - 'bash ./travis/test_coverage.sh;'

after_success:
  - bash <(curl -s https://codecov.io/bash)